### ISSUE TITLE
Syntax Highlighting Not Working For Some Characters on Windows VS Code

### ISSUE THREAD

**Issue by kiwiplan-us** [canadaduane/vscode-notes#1]
The syntax highlighting does not work for some characters on Windows VS Code without adding some custom settings such as 

```
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "keyword.operator.notes",
            "settings": {
                "foreground": "#92b630"
            }
        },
        {
            "scope": "variable.language.notes",
            "settings": {
                "foreground": "#92b630",
                "fontStyle": "italic"
            }
        }
    ]
}

```

After adding the above to settings, Note syntax highlighting only works with

```
# this #
**this**
- this
-> this
--> this
==> this
`this`
"this"
1. this
2. this
```
Items that do not work are and remain gray or white are

```
! this !
// this
[this]
```

**Comment by canadaduane** [comment]
Hey, thanks for the report. When you say "for some characters" do you mean all characters? Or are some characters in a line highlighting, while others aren't?

Could it be that your theme uses less common syntax namespaces? Could you maybe try another theme, e.g. `Dark+`?

<img width="719" alt="image" src="https://user-images.githubusercontent.com/129/54211339-bf85fd00-44a6-11e9-9488-9f65bdfae002.png">

**Comment by kiwiplan-us** [comment]
This worked, I guess my theme does not work well with it.

**Comment by canadaduane** [comment]
Thanks for checking. Let me know if you see any other issues. I'll close this now.
