### ISSUE TITLE
New Feature: Lists

### ISSUE THREAD

**Issue by MerryCello** [canadaduane/vscode-notes#10]
It would be nice to be able to have a list (unlisted, ordered, etc.) that continues on enter press.
Example:
1. Press Enter
2. 
--^-- Boom! Adds the next list line

Thank you!

**Comment by canadaduane** [comment]
That's a good idea! Is it something you are thinking of adding?

**Comment by MerryCello** [comment]
I could contribute if that's how the repo is managed!

**Comment by canadaduane** [comment]
Absolutely. I'd be happy to review a PR and add auto lists if you're up for it.

**Comment by MerryCello** [comment]
I honestly don't know anything about creating/editing VS code extensions, but I guess I can learn. It looks like it's just some js.

**Comment by canadaduane** [comment]
Arbitrarily picking this issue to close as it is duplicated by the above
