### ISSUE TITLE
Light green items showing as blue

### ISSUE THREAD

**Issue by codemazey** [canadaduane/vscode-notes#11]
In the documentation it shows the following items as light green:
 - #tag#
 - numbers in numbered lists
 - arrow
 - double arrow

in the current version these are all showing up with the same blue colour as *emphasis*,  heading:, == special heading ==

Running VSCode 1.50.1

**Comment by codemazey** [comment]
![image](https://user-images.githubusercontent.com/37877157/97782928-5e83cf00-1b8c-11eb-9425-70a6474fa6cd.png)

**Comment by canadaduane** [comment]
Oh, strange. Could you run Cmd+Shift+P "Inspect Editor Tokens and Scopes" on those items and see if the "textmate scopes" includes "variable.language.notes"?

Here's what I'm seeing on Notes version 1.1.0:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/129/97788814-4eb2bd80-1b81-11eb-930b-efc09372df3b.png">

**Comment by codemazey** [comment]
yes it does for the arrow: (showing blue but green expected)
-->3 chars
------------------------------
language notes
standard token type Other
foreground #569CD6
background #1E1E1E
contrast ratio 5.65
------------------------------
textmate scopes variable.language.notes
source.notes
foreground variable.language
{ "foreground": "#569CD6" }

but for the #tag# (also showing blue but green expected) it is not there:

#tag#5 chars
------------------------------
language notes
standard token type Other
foreground #569CD6
background #1E1E1E
contrast ratio 5.65
------------------------------
textmate scopes variable.language.notes
nothing.notes
source.notes
foreground variable.language
{ "foreground": "#569CD6" }

unordwered list is showing blue where green expected, here is the result of
one of those:

-·2 chars
------------------------------
language notes
standard token type Other
foreground #569CD6
background #1E1E1E
contrast ratio 5.65
------------------------------
textmate scopes variable.language.notes
source.notes
foreground variable.language
{ "foreground": "#569CD6" }


and ordered lists are showing as white (green expected), here are the
properties for one of those:

1.·3 chars
------------------------------
language notes
standard token type Other
foreground #D4D4D4
background #1E1E1E
contrast ratio 11.24
------------------------------
textmate scopes keyword.operator.notes
source.notes
foreground keyword.operator
{ "foreground": "#D4D4D4" }

I should mention this is running on Windows 10. Could be some Microsoft
weirdness, perhaps.

best regards,
David.

weirdly the numbered lists feature is now showing up as white numbers
(green expected)

**Comment by canadaduane** [comment]
What color theme are you using?

**Comment by codemazey** [comment]
I am using the theme "Dark+ (Default Dark)" - one of the out of the box
themes for VSS.
I tried flipping through a number of themes - I can see this does affect
it, so the numbered lists have a different colour in nearly any other theme.
(Is there a theme you recommend for testing?)

**Comment by canadaduane** [comment]
Dark+ should be fine. I'm trying to replicate the issue here on my end, but so far no dice. It's strange. When I use Dark+ I see the same colors as are in the docs. I personally prefer a theme called "Ayu Dark Bordered" but that shouldn't be necessary for you to switch to.

My best guess at this point is that some other plugin that you have installed is affecting coloration? I can't think of anything else that would be causing this.

**Comment by canadaduane** [comment]
This document might be helpful in finding out what possible things could affect color: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by codemazey** [comment]
Hi Duane,
I just wanted to say thank you and express my appreciation that you have
made this color scheme (and a ton of other code too!) for the benefit of
everyone.

Thanks also for your time having a look at this issue.
I have switched to Ayu Dark (Bordered)and it is looking great. It is still
using the same colour for one or two items but it's not a life-threatening
issue. I uninstalled all colorscheme plugins, then reinstalled notes and
then Ayu, and it's looking like this now:
[image: image.png]
I do have a bunch of other plugins. and as you say it seems likely one of
them is causing it, in any event it seems highly likely it's some once-off
weird setting on my local machine only, because no-one else is reporting
it, so we know the code is good.

I'm impressed by the huge amount of code in your GitHub repo. On my to-do
list now is to get involved with some open-source projects myself.

All the best from the UK !
David Mockridge.

**Comment by codemazey** [comment]
had a slight typo in that test screen, this includes the *text*
[image: image.png]

**Comment by canadaduane** [comment]
Thanks David! If you're out looking for a fun project to join, you might like to check out [Relm](https://github.com/relm-us/relm]. We're passionate about bringing people together online in a way that focuses more on fulfilling our human need for belonging, connection, and collaboration than the current "social networks" do. We have a big challenge in front of us--a game-like virtual world that does video conferencing in a more psychologically healthy way than Zoom. Anyway, thanks again for your positive note! I'll close this now but feel free to reach out to me personally if you have any questions (my github profile includes my email).
