### ISSUE TITLE
Set seperate keybinding for default "notes.cycleTaskForward" keybinding on Windows 

### ISSUE THREAD

**Issue by dmattera** [canadaduane/vscode-notes#12]
Apparently, when you set a keybinding with the "cmd" modifier, VS Code automatically translates it to the Windows key on Windows. 

So defining the keybinding like so:

````
{
        "command": "notes.cycleTaskForward",
        "key": "cmd+l",
        "when": "editorTextFocus"
 }
````
sets it as this on Windows:

![image](https://user-images.githubusercontent.com/13613522/98973677-08931d80-24e2-11eb-954b-b288d72b4058.png)

`Win+L` is a global OS-level keybinding in Windows that can't be overridden and so I would suggest something along the lines of:

````
{
        "command": "notes.cycleTaskForward",
        "key": "cmd+l",
        "when": "editorTextFocus && !isWindows"
 },
{
        "command": "notes.cycleTaskForward",
        "key": "ctrl+l",
        "when": "editorTextFocus && isWindows"
 }
````

**Comment by canadaduane** [comment]
BTW thanks for reporting this (long ago) and noting a way to fix it. I still haven't gotten around to it, but intend to next time I update the add-on.
