### ISSUE TITLE
notes.cycleTaskForward	cmd+L

### ISSUE THREAD

**Issue by instanetk** [canadaduane/vscode-notes#13]
Pressing ⌘+L does not do anything to my TODO items list.

```
TODO:

[ ] Check these notes. 

```
Putting the cursor at the end of the line above and pressing ⌘+L has no effect. Neither does putting the cursor in between the brackets. 

I made sure the keybinding exists.

I am on Big Sur 11.1 (20C69).
VS Code Version: 1.52.0

**Comment by instanetk** [comment]
The problem was being caused by preexisting Key Chords in my Keyboard Shortcuts.

The status bar displayed: Pressed ⌘+L, waiting for second key of chord.

Another extension, Live Server, had the key binding ⌘+L ⌘+O and VS Code was awaiting a second key press.

By changing this extension's key chord to ⌘+S ⌘+O it left ⌘+L available for Notes.

**Comment by canadaduane** [comment]
I'm glad this was resolved. Thanks for the solution/note for others!
