### ISSUE TITLE
Color syntax doesn't work with Panda Theme

### ISSUE THREAD

**Issue by Shouri14** [canadaduane/vscode-notes#15]
The color highlights for list, --->, ! Note ! ......doesn't seem to work with panda extension.

With Panda Theme : 
![image](https://user-images.githubusercontent.com/37922572/119078423-2a56eb00-b9c4-11eb-8300-7d0ff1d69e5d.png)

 Without Panda Theme : 
![image](https://user-images.githubusercontent.com/37922572/119078475-45c1f600-b9c4-11eb-8705-0c32b3508f1c.png)

Panda theme is quite popular, is there any way we can fix/workaround this. Thank you.

**Comment by canadaduane** [comment]
There is a workaround available by configuring custom token colors. See https://github.com/canadaduane/vscode-notes#configuration

**Comment by canadaduane** [comment]
I'm going to close this as I think the custom token colors fit the bill. Feel free to open another if not.
