### ISSUE TITLE
Syntax highlighting usage wrongly described. 

### ISSUE THREAD

**Issue by maikelthedev** [canadaduane/vscode-notes#16]
In the README.md file it says

> When adding code snippets, you can use the following language indicators after a triple-backtick to get syntax highlighting for that language

But then all the way to the top of the file we see an example with square brackets. I have checked and it does work with square brackets, but there's no mention of this in that paragraph. It should be changed to avoid confusion.

**Comment by canadaduane** [comment]
Ah thanks! I'll fix that.

**Comment by canadaduane** [comment]
Done.

**Comment by maikelthedev** [comment]
Thank you ^^
