### ISSUE TITLE
Link Pattern Functionality

### ISSUE THREAD

**Issue by jvansant** [canadaduane/vscode-notes#17]
I love this extension! I'm hoping I can get a little support configuring some more complex links. I use BugHerd for issue tracking. The URL's are formatted as so:

https://www.bugherd.com/projects/{project-number}/tasks/{task-number}

We would need to use two variables in the link; one for project-number and one for task-number. Is this currently possible?
If it is, I would also like to link project-number to a project-name attribute using some sort of key-value map. The goal is to achieve this link setup and format:

```
projects{
"abc":"123",
"def":"456"
}
[https://bugherd.com/projects/$1/tasks/$0]

TODO:
[ ] (1 abc)
[ ] (29 def)
```

The above links would direct to:
--> https://bugherd.com/projects/123/tasks/1
--> https://bugherd.com/projects/456/tasks/29

**Comment by canadaduane** [comment]
Hi! Glad you're making good use of this :)

Yes,  you can use multiple patterns (one per project) to achieve what you're after:

```
Project Patterns:
[/(\d+)\s+abc/ -> https://bugherd.com/projects/123/tasks/$1]
[/(\d+)\s+def/ -> https://bugherd.com/projects/456/tasks/$1]

Clickable Links:
(1 abc)
(29 def)
```

Hope that helps!

**Comment by jvansant** [comment]
@canadaduane Yes! The solution was much simpler than I expected. After looking through the source code it is very clear. And a good chance to brush up on regex. Thanks a bunch!
