### ISSUE TITLE
Screenshot color palette?

### ISSUE THREAD

**Issue by cig0** [canadaduane/vscode-notes#2]
Hi,

I love the color theme from the screenshot in the README.md file (https://github.com/canadaduane/vscode-notes/raw/master/images/vscode-notes-sample.png); do you have the color palette at hand by chance?

Thanks!

**Comment by canadaduane** [comment]
I think I'm just using the default "Dark+" theme from Visual Studio Code. Are you looking for the actual color values of the theme?

**Comment by canadaduane** [comment]
Hi Martin--yes, see
https://github.com/canadaduane/vscode-notes/blob/master/syntaxes/custom-colors.json
