### ISSUE TITLE
Link pattern functionality

### ISSUE THREAD

**Issue by Axlyted** [canadaduane/vscode-notes#20]
Hey, is it possible to define a pattern in a configuration file and then use it automatically?

For example, put this:
[/ABC-\d+/ -> https://abc-project.atlassian.net/browse/$0]
somewhere at .vscode/settings.json and then be able to click links whenever I see this string
ABC-1243

**Comment by canadaduane** [comment]
Not currently, but I like the idea. A PR would be welcome. Or, I might get
to it some time :)

**Comment by canadaduane** [comment]
Implemented by Axlyted's PR #22
