### ISSUE TITLE
vscode is aligned with master branch instead of main branch

### ISSUE THREAD

**Issue by Axlyted** [canadaduane/vscode-notes#23]
![image](https://user-images.githubusercontent.com/14972469/149757197-9889fc34-0edf-41fc-bc3c-6aceb8e31a01.png)

20/10/2020 is the last time the master branch was updated so I assume this is the issue. Can you fix this up?

**Comment by Axlyted** [comment]
@canadaduane  I mean, it's kind of preventing me from using the feature I submitted earlier since it gives me the master version instead of main's.

**Comment by canadaduane** [comment]
I haven't published a new version yet, so it isn't showing up in the Microsoft marketplace.

Edit to add: I'm on a new laptop since the previous version publication, so I have to go through the Microsoft-hoopalooza to get publishing keys etc.

**Comment by canadaduane** [comment]
Published 1.2.1. Note that I changed the way config works. The "Item" is now the regex pattern, and the "Value" is now the URL/link.

**Comment by Axlyted** [comment]
Great, thank you! :+1:
