### ISSUE TITLE
alt+l (alt+L) is at mac os the @ character

### ISSUE THREAD

**Issue by dark-kitt** [canadaduane/vscode-notes#25]
Hey Duane,

great work. Your vscode-notes plugin looks really good, but I have one little problem with the keybindings. The alt+l (alt+L) command is at mac os the @ character. So every time I or others try to write @ in any file your plugin overwrites it and handles your special command for [x], [!] etc., so I would be very happy if you remove this command or define some other command. Or you define something like:

```
"keybindings": [
	{
		"command": "notes.cycleTaskForward",
		"key": "ctrl+l",
		"mac": "cmd+l",
		"when": "editorTextFocus"
	},
	{
		"command": "notes.cycleTaskBackward",
		"key": "alt+l",
		"mac": "crtl+l",
		"when": "editorTextFocus"
	}
]
```

Please let me know if you agree. ;)

Best
Steffen

**Comment by canadaduane** [comment]
Thanks for reporting!

I've changed the default shortcut keys to ctrl+l (cmd+l on Mac) and ctrl+shift+l (cmd+shift+l on Mac). v1.3.0

I hope that helps.
