### ISSUE TITLE
Ordered bullet lists don't highlight anything using default Dark+ theme.

### ISSUE THREAD

**Issue by Birthday-Cakeman** [canadaduane/vscode-notes#29]
As the title states, syntax highlighting does nothing when ordered lists are created. One may think that this is a theme issue, as I say stated in another issue, but I'm currently using the recommended default Dark+. As you will see below, all other highlights seem to work fine, besides the one mentioned. This is all using defaults settings and configurations.

![No-Highlight](https://github.com/canadaduane/vscode-notes/assets/29213472/157ecfad-2d19-4533-8968-1410842943d7)

**Comment by Birthday-Cakeman** [comment]
Never mind! I'm a big dumby, and I didn't override my color settings. After doing so, it works great!

**Comment by canadaduane** [comment]
I'm curious what was overridden, and why it was necessary in your case. Do you have some custom color settings beyond the default Dark+ theme?

**Comment by Birthday-Cakeman** [comment]
Hi Duane,

I didn't have any custom color settings to speak of. Not sure what was
causing all of the issues, but nonetheless, overriding the default colors
seemed to do the trick.
