### ISSUE TITLE
Adding support for Windows batch file code in my *.Notes files

### ISSUE THREAD

**Issue by mkanet** [canadaduane/vscode-notes#3]
I am trying to add support for Windows batch file code in my *.Notes files.  However, after I add below.. and, restart VSCode, batch file code is still ignored in my *.Notes files.  Could you please tell me what I'm doing wrong?

**notes.tmLanguage.json**
```
    {
      "comment": "Batch",
      "begin": "(\\[)(bat|cmd|batch)(\\])",
      "beginCaptures": {
        "1": {
          "name": "string.regexp.notes"
        },
        "2": {
          "name": "markup.bold.notes"
        },
        "3": {
          "name": "string.regexp.notes"
        }
      },
      "end": "(\\[)(\\\\?\\/?(end|bat|cmd|batch))(\\])",
      "endCaptures": {
        "1": {
          "name": "string.regexp.notes"
        },
        "3": {
          "name": "markup.bold.notes"
        },
        "4": {
          "name": "string.regexp.notes"
        }
      },
      "patterns": [
        {
          "include": "source.batch"
        }
      ]
    },
```

For example, if I add the below code in my .notes file, it is ignored:

[batch]
    @echo off
    start microsoft-edge:http://google.co.uk
    ping -n 2 127.0.0.1
    for /f %%a in ('cmdow /f /t ^| findstr ApplicationFrameHost.*Google') do (
      cmdow %%a /mov 1000 100
      cmdow %%a /siz 200 500
    )
[end]

**Comment by canadaduane** [comment]
I don't see anything obviously wrong... have you had any luck figuring this
out?

**Comment by mkanet** [comment]
Thanks for the reply back.  For some reason it just doesn't.  I didnt have any problems adding PowerShell support using the same method.

**Comment by canadaduane** [comment]
This issue has been open for a while, and I don't intend on adding this functionality without a PR, so I will close it soon unless someone objects.
