### ISSUE TITLE
Any plan for tag?

### ISSUE THREAD

**Issue by timyilong** [canadaduane/vscode-notes#4]
it is really cool extension. Do u think about the plan add tag feature. It is really helpful.

**Comment by canadaduane** [comment]
I haven't considered tagging before. It's a good idea, although I think it
may be challenging. What do you imagine the interface to be like? How would
you list the tags, or search tags? Do you have any examples of this being
done well in other editors or extensions?

**Comment by canadaduane** [comment]
This issue has been open for a while. Without more clarification, I will close it soon, however.
