### ISSUE TITLE
Symbols & numbers with highlighting

### ISSUE THREAD

**Issue by cameronhanton** [canadaduane/vscode-notes#5]
I noticed that when you used asterisk or exclamation marks to highlight or emphasis things it breaks when you try and use a symbol (^&-) or any number (123) which is quite annoying

**Comment by canadaduane** [comment]
This is what I'm seeing:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/129/68693845-41965c00-0535-11ea-9c75-aa117f2425f2.png">

It looks like the behavior you're describing is only for asterisks? Or is something else happening for you?

**Comment by h7x4** [comment]
I'd like to leave a comment on this one too. Emphasis doesn't highlight text with symbols, just as shown in the two last lines of your example.
